# Generated by Django 4.2 on 2023-04-14 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_username_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email",
            new_name="username",
        ),
    ]
