# Generated by Django 4.2 on 2023-04-15 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="email",
        ),
    ]
