# Generated by Django 4.2 on 2023-04-15 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
