# Generated by Django 4.2 on 2023-04-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
