# Generated by Django 4.2 on 2023-04-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
