# Generated by Django 4.2 on 2023-04-15 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_user_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ADDITION", "Addition"),
                            ("SUBTRACTION", "Subtraction"),
                            ("MULTIPLICATION", "Multiplication"),
                            ("DIVISION", "Division"),
                            ("SQUARE_ROOT", "Square Root"),
                            ("RANDOM_STRING", "Random String"),
                        ],
                        max_length=14,
                    ),
                ),
                ("cost", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("amount", models.FloatField()),
                ("user_balance", models.FloatField()),
                ("operation_response", models.CharField(max_length=32)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "operation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.operation"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
