# Generated by Django 4.2 on 2023-04-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_operation_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("ADDITION", "Addition"),
                    ("SUBTRACTION", "Subtraction"),
                    ("MULTIPLICATION", "Multiplication"),
                    ("DIVISION", "Division"),
                    ("SQUARE_ROOT", "Square Root"),
                    ("RANDOM_STRING", "Random String"),
                ],
                max_length=14,
                unique=True,
            ),
        ),
    ]
