# Generated by Django 4.2 on 2023-04-16 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_operation_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="data",
            new_name="date",
        ),
    ]
