# Generated by Django 4.2 on 2023-04-16 00:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_rename_data_record_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="operation_id",
            new_name="operation",
        ),
        migrations.RenameField(
            model_name="record",
            old_name="user_id",
            new_name="user",
        ),
    ]
